spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb          # in-memory database (destroyed on shutdown)
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: create              # can be 'create', 'create-drop', 'validate', or 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
